### ISSUE TITLE
[Feature request] Display "Live Training" web app

### ISSUE THREAD

**Issue by JamesDBartlett3** [Invvard/EZLayoutDisplay#100]
**Is your feature request related to a problem? Please describe.**
Ergodox EZ just released a new tool to help new users practice their custom keyboard layout, called "Live Training." It displays the user's keymap in a web browser window, and updates to reflect the current state of the keyboard, including key presses (individual and multiple) and layer changes. 

**Describe the solution you'd like**
I'd love to see this incorporated into the EZLayoutDisplay window, so I can easily bring it up when I need it, but otherwise leave it hidden. 

**Describe alternatives you've considered**
I thought about trying to use some "web widget" type application to slide a browser window onto the screen when a hotkey is pressed, but I thought it would be best to suggest the feature here first, since this application is specifically designed for this purpose, and integrating with the Live Training application would be more than just a single feature -- it would add all of the features of Live Training, many of which are not yet included in EZLayoutDisplay. If you don't have the time to work on it, I totally understand. 

**Additional context**
Animation demonstrating what it looks like:
https://blog.zsa.io/821dca4717b07d977f8531334ee8b57e/live_training.gif

Official link to the Live Training web app: 
https://configure.ergodox-ez.com/train

Erez Zuckerman's blog entry about the new feature:
https://blog.zsa.io/1912-live-training/

Demo Video: 
https://www.youtube.com/watch?v=ZBF5NUYHWGc

**Comment by Invvard** [comment]
Hi James

First, I'd like to apologize about this late answer. I spent few weeks away for the holydays and I forgot to answer your request.

Thank you for your request, it is indeed a very good idea and something I've been thinking about since the first days of development. Before the new ZSA live training feature, I thought I'd need to add more hooks but now, there's a lot more possibilities available.

Right now, sadly, I've very little free time to put into this project (just bought a new home and I have work to do in it) but as soon as I'll be able to get back to my home Ergodox, I'll implement this feature ! In the mean time, any contribution is very much welcome :D

I wish you a great new year !
