### ISSUE TITLE
[BUG] Program errors instead of loading any layouts: Parameter name does not exist

### ISSUE THREAD

**Issue by Voidlighter** [Invvard/EZLayoutDisplay#124]
## Actual Behavior
Every layout I try to paste doesn't work, instead saying `Parameter name: Hash ID "default" does not exist`
![image](https://github.com/Invvard/EZLayoutDisplay/assets/96223540/879c382c-0a04-4244-92e3-6761687b3f59)
![image](https://github.com/Invvard/EZLayoutDisplay/assets/96223540/6a22289a-22f1-4951-8bfe-1617194ab023)

## To Reproduce
  1. Launch EZLayoutDisplay
  2. Right-click the EZLayoutDisplay tray icon; Select settings.
  3. EZLayoutDisplay will error `Parameter name: Hash ID "default" does not exist`
  4. Select OK and paste another URL in, in my case [https://configure.zsa.io/moonlander/layouts/y9gan/latest/0](https://configure.zsa.io/moonlander/layouts/y9gan/latest/0)
  5. EZLayoutDisplay will error `Parameter name: Hash ID "y9gan" does not exist`

## Expected Behavior
The settings should load, no errors should occur, especially just loading the default layout.

## Specifications
  - EZLayout Version: both v1.3.0-beta and v1.2.1
  - ErgoDox Layout Configurator URL: [https://configure.ergodox-ez.com/layouts/default/latest/0](https://configure.ergodox-ez.com/layouts/default/latest/0) and [https://configure.zsa.io/moonlander/layouts/y9gan/latest/0](https://configure.zsa.io/moonlander/layouts/y9gan/latest/0)
  - Operating System (incl. Version): Windows 11 Pro 23H2
  
## Additional context
If it's anything like the [previous bug report](https://github.com/Invvard/EZLayoutDisplay/issues/101) that looked like this, Oryx probably updated and this program is no longer able to read/retrieve information properly.

As an aside, a more future-proof way to fix this (probably) would be to allow reading from the code or firmware files. I don't know how hard or different that would be, but I've begun editing the QMK of my layout, so giving those to the program would be a lot easier for me anyway. Those files are also easily available to download for any layout from Oryx, so it would be helpful to all users in the future if Oryx updates in a way that this program can no longer read from it.

**Comment by Invvard** [comment]
Hi @Voidlighter,

Sorry for the response delay, I did not receive a notification for your issue.

As you can see in this [blog post from ZSA](https://blog.zsa.io/keymapp/?mc_cid=c98c21cf26&mc_eid=e0699d92ff), they just released publicly their very own app called [Keymapp](https://www.zsa.io/flash).
I tried it and it offers a lot of features I wanted to add to EZLayoutDisplay but never had time to so...

You may have already understood it, but I will retire this app for good. I don't have time anymore to support it since I became a father for 2 twin girls recently, and to be honest, I haven't been active on this project for quite a while.

EZLayoutDisplay is dead, long live Keymapp!
