### ISSUE TITLE
Layout window does not get focus on Hyper+Space hotkey

### ISSUE THREAD

**Issue by Invvard** [Invvard/EZLayoutDisplay#36]
## Expected Behavior
When hitting the Hyper+Space hotkey to display the layout window, the said window appears and has focus which will allow user to hide it by hitting Escape or changing app (EZLD loses focus)

## Actual Behavior
When hitting the Hyper+Space hotkey to display the layout window, the said window does not get the focus and flashes in the task bar. User need to select it (Alt+Tab or clicking the task bar) to see it.
This behavior is not constant and sometimes it will work as expected.

## Steps to Reproduce the Problem

  1. Launch app,
  2. Hit Hyper+Space hotkey,
  3. Layout window doesn't appear and flashes in task bar.

## Specifications

  - EZLayout Version: 0.2.0.2001
  - Operating System (incl. Version) : Windows 10 x64

**Comment by JamesDBartlett** [comment]
I've noticed that it seems to be related to the focus state of the app window the last time it was closed. When I hit Escape to dismiss the window, it always comes back focused, but if I click away from the window instead of hitting escape, it loses focus before it disappears. Then, when I try to summon it again at a later time, it retains the unfocused state from navigated away from previously. 

I'm not a .NET developer, but if you can either give the window a property of "always on top" or maybe trigger a "bring to front" event after the window is launched, either way, that would probably fix it.

**Comment by Invvard** [comment]
Thank you for your analysis, I had not understand the fact that the window loses focus first when we click away.
> I'm not a .NET developer, but if you can either give the window a property of "always on top" or maybe trigger a "bring to front" event after the window is launched, either way, that would probably fix it.

Yes indeed, I found that "Always on top" is the way to ensure that window appears as expected but I'll dig into the "bring to front" idea. It should be fixed in the next release.

**Comment by JamesDBartlett** [comment]
Splendid! Glad I could provide the assist, even if all I did was just line you up for the winning shot. ;-)

**Comment by Invvard** [comment]
Fixed in the upcoming v.1.1.0.0

**Comment by JamesDBartlett** [comment]
I don't know how I missed that this had been fixed, but I just updated to the latest release, and it works great! Thanks for writing this highly useful tool!
